title: Project title in sentence case
hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Install or update Thonny
    completion:
      - engaged
  - title: Add the MicroPython firmware
  - title: RGB LED
  - title: Check ntfy
  - title: Change colour if ntfy
  - title: Touch control
  - title: Challenge
    challenge: true
    completion:
      - external
