title: Friend frame
hero_image: images/banner.png
description: Build a photo frame that changes colour when you get a notification from a friend.
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Install or update Thonny
    completion:
      - engaged
  - title: Add the MicroPython firmware
  - title: RGB LED
  - title: Connect to WiFi
  - title: Choose a topic
  - title: Check for notifications
  - title: Respond to specific messages
  - title: Build your friend's frame
  - title: Challenge
    challenge: true
    completion:
      - external
